package reports;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;

public class ReportGenerator {

    public void generateReport() {
        String fileName = "system_report.txt";

        try (BufferedWriter writer = new BufferedWriter(new FileWriter(fileName))) {
            writer.write("📘 Nkwa Real Estate Expenditure Management System - Documentation\n");
            writer.write("=================================================================\n\n");

            writer.write("1️⃣ DATA STRUCTURE JUSTIFICATIONS\n");
            writer.write("--------------------------------\n");
            writer.write("• HashMap (Expenditures): Used for fast retrieval by code (O(1) average).\n");
            writer.write("• HashSet (Categories): Ensures uniqueness and supports fast lookups.\n");
            writer.write("• Map (Accounts): Associates bank account IDs with details and expenditures.\n");
            writer.write("• Queue (Receipts): FIFO structure for receipt processing in order of submission.\n");
            writer.write("• Graph (Account Relationships): Models internal transfers as directed edges.\n");
            writer.write("• List/ArrayList: Used for sorting and intermediate storage.\n");
            writer.write("• TreeMap: Used to store burn rate with monthly ordering.\n\n");

            writer.write("2️⃣ SEARCHING TECHNIQUES\n");
            writer.write("-------------------------\n");
            writer.write("• Linear Search: Used to find expenditures by category, date range, amount, or account.\n");
            writer.write("  - Justified since we're not using external libraries or databases.\n");
            writer.write("  - Time Complexity: O(n)\n\n");

            writer.write("3️⃣ SORTING TECHNIQUES\n");
            writer.write("------------------------\n");
            writer.write("• Insertion Sort: Used for sorting expenditures by category or date.\n");
            writer.write("  - Easy to implement manually.\n");
            writer.write("  - Stable and works well for small to moderate datasets.\n");
            writer.write("  - Time Complexity: O(n²) worst, O(n) best (already sorted).\n\n");

            writer.write("4️⃣ COMPLEXITY ANALYSIS\n");
            writer.write("------------------------\n");
            writer.write("• HashMap Lookup: O(1) average, O(n) worst\n");
            writer.write("• HashSet Add/Search: O(1) average, O(n) worst\n");
            writer.write("• Queue Operations (enqueue/dequeue): O(1)\n");
            writer.write("• BFS for graph traversal: O(V + E)\n");
            writer.write("• Insertion Sort: O(n²) worst, Ω(n) best\n\n");

            writer.write("✅ REPORT COMPLETED.\n");
            writer.write("Generated by: ReportGenerator.java\n");

            System.out.println("📄 system_report.txt has been generated successfully.");

        } catch (IOException e) {
            System.out.println("❌ Error generating report: " + e.getMessage());
        }
    }
}
